name = "RustyMTR"
author = "Rustyy"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16ce4526f8e14edde8c8da3c697b66cdc43490841bf634bd694311fdc77a9713"

[versions]
fabric = "0.16.5"
minecraft = "1.20.4"
